"""Regression gates for the frozen desktop contract.

These tests are intentionally offline and never read the user's Pulsaria data.
"""

from __future__ import annotations

import json
import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class MvpContractTests(unittest.TestCase):
    def test_local_demo_assets_are_bundled(self) -> None:
        for index in range(1, 7):
            self.assertTrue((ROOT / "public" / "demo" / f"demo-{index:02d}.jpg").is_file())
            self.assertTrue((ROOT / "public" / "demo" / f"demo-{index:02d}.mp4").is_file())

    def test_every_frontend_ipc_command_is_registered(self) -> None:
        frontend_commands: set[str] = set()
        for directory in (ROOT / "app", ROOT / "components", ROOT / "hooks", ROOT / "lib"):
            for path in directory.rglob("*.ts*"):
                text = path.read_text(encoding="utf-8")
                frontend_commands.update(
                    re.findall(r"\binvoke(?:<[^;]+?>)?\(\s*['\"]([a-zA-Z0-9_]+)['\"]", text)
                )

        composition_root = (ROOT / "src-tauri" / "src" / "main.rs").read_text(encoding="utf-8")
        registered = set(re.findall(r"commands::([a-zA-Z0-9_]+)", composition_root))
        missing = sorted(frontend_commands - registered)
        self.assertEqual(missing, [], f"Frontend IPC commands missing from Tauri: {missing}")

    def test_setup_sends_structured_mvp_settings_payload(self) -> None:
        hook = (ROOT / "hooks" / "use-processing-settings.ts").read_text(encoding="utf-8")
        self.assertIn(
            "invoke<ProcessingSettings>('save_mvp_settings', {\n        input: {",
            hook,
            "The setup wizard must pass MvpSettingsInput under Tauri's input argument.",
        )
        self.assertIn(
            "downloadDir: setup.downloadDir || ''",
            hook,
            "The structured payload must retain the selected media directory.",
        )

    def test_setup_floors_storage_recommendations_before_persisting(self) -> None:
        modal = (ROOT / "components" / "ProcessingSetupModal.tsx").read_text(encoding="utf-8")
        self.assertIn(
            "Math.floor(normalized.quotaBytes / GIB)",
            modal,
            "Native storage recommendations must not round above the safe free-space boundary.",
        )
        self.assertIn(
            "Math.floor(fallbackRecommendation.quotaBytes / GIB)",
            modal,
            "Fallback storage recommendations must use the same safe flooring rule.",
        )

    def test_native_settings_use_named_tauri_argument(self) -> None:
        panel = (ROOT / "components" / "SettingsPanel.tsx").read_text(encoding="utf-8")
        context = (ROOT / "lib" / "settings-context.tsx").read_text(encoding="utf-8")
        self.assertIn(
            ">('save_app_settings', {\n                    settings: {",
            panel,
            "SettingsPanel must pass AppSettingsSnapshot under Tauri's named settings argument.",
        )
        self.assertIn(
            "invoke('save_app_settings', {\n                                    settings: {",
            context,
            "Native localStorage migration must use the same Tauri argument contract.",
        )

    def test_python_workers_have_one_canonical_source(self) -> None:
        config = json.loads((ROOT / "src-tauri" / "tauri.conf.json").read_text(encoding="utf-8"))
        resources = config["bundle"]["resources"]
        canonical_workers = sorted(path.name for path in (ROOT / "python-workers").glob("*.py") if not path.name.startswith("test_"))
        packaged_workers = sorted(
            Path(source).name
            for source, destination in resources.items()
            if source.startswith("../python-workers/")
            and destination == f"resources/python-workers/{Path(source).name}"
        )
        duplicated_sources = list((ROOT / "src-tauri" / "resources" / "python-workers").glob("*.py"))

        self.assertEqual(packaged_workers, canonical_workers)
        self.assertEqual(duplicated_sources, [], "Bundled worker copies must be generated by Tauri")

    def test_portable_python_can_import_canonical_workers(self) -> None:
        runtime_path = ROOT / "src-tauri" / "resources" / "python" / "python311._pth"
        runtime_paths = {
            line.strip().replace("/", "\\")
            for line in runtime_path.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        }
        self.assertIn(
            r"..\..\..\python-workers",
            runtime_paths,
            "Portable Python must include the canonical worker directory",
        )


if __name__ == "__main__":
    unittest.main()
