// ============================================================
// PulsarSemanticLayer — Domain Entities
// Capa semántica independiente del dominio multimedia.
// ============================================================

export type EntityType = 
  | 'asset'      // Archivo binario (video, audio, imagen)
  | 'media'      // Recurso multimedia (video, audio)
  | 'video'      // Video específico
  | 'audio'      // Audio específico
  | 'image'      // Imagen/thumbnail
  | 'source'     // Fuente externa (URL, plataforma)
  | 'creator'    // Autor/creador
  | 'tag'        // Etiqueta semántica
  | 'playlist'   // Playlist de Pulsar
  | 'collection' // Colección semántica
  | 'thumbnail'  // Thumbnail asociado
  | 'transcript' // Transcripción de audio
  | 'project';   // Proyecto/ámbito

export interface SemanticEntity {
  id: string;           // Estable: prefijo + hash o UUID
  type: EntityType;
  label?: string;
  metadata: Record<string, any>;
  createdAt: string;
  updatedAt: string;
}

export interface AssetEntity extends SemanticEntity {
  type: 'asset';
  metadata: {
    path: string;        // Ruta relativa dentro de library/
    mimeType: string;
    size: string;        // bytes como string para evitar overflow
    checksum: string;    // SHA-256 o MD5
    storageProvider: string; // 'local' por ahora
  };
}

export interface MediaEntity extends SemanticEntity {
  type: 'media';
  metadata: {
    assetId: string;
    mediaType: 'video' | 'audio' | 'image';
    duration?: string;
    width?: number;
    height?: number;
    fps?: number;
    codec?: string;
    bitrate?: string;
  };
}

// @ts-expect-error: narrowing literal type from parent
export interface VideoEntity extends MediaEntity {
  type: 'video';
  metadata: MediaEntity['metadata'] & {
    platform?: string;    // 'tiktok', 'youtube', 'instagram'
    externalId?: string;  // ID en la plataforma origen
  };
}

// @ts-expect-error: narrowing literal type from parent
export interface AudioEntity extends MediaEntity {
  type: 'audio';
  metadata: MediaEntity['metadata'] & {
    language?: string;
    codec?: string;
  };
}

// @ts-expect-error: narrowing literal type from parent
export interface ImageEntity extends MediaEntity {
  type: 'image';
  metadata: MediaEntity['metadata'] & {
    width: number;
    height: number;
  };
}

export interface SourceEntity extends SemanticEntity {
  type: 'source';
  metadata: {
    url: string;
    provider: string;     // 'tiktok', 'youtube', 'instagram', 'generic'
    platform: string;
    externalId?: string;
  };
}

export interface CreatorEntity extends SemanticEntity {
  type: 'creator';
  metadata: {
    name: string;
    platform?: string;
    externalId?: string;
  };
}

export interface TagEntity extends SemanticEntity {
  type: 'tag';
  metadata: {
    normalized: string;   // lowercase, sin espacios
    category?: string;    // 'topic', 'style', 'trend', 'custom'
  };
}

export interface PlaylistEntity extends SemanticEntity {
  type: 'playlist';
  metadata: {
    pulsarPlaylistId: string; // Referencia al ID de Pulsar
    color?: string;
    autoGenerated?: string;    // 'true' | 'false'
    topicKeywords?: string;    // JSON array como string
  };
}

export interface CollectionEntity extends SemanticEntity {
  type: 'collection';
  metadata: {
    description?: string;
  };
}

export interface ThumbnailEntity extends SemanticEntity {
  type: 'thumbnail';
  metadata: {
    assetId: string;
    width: number;
    height: number;
  };
}

export interface TranscriptEntity extends SemanticEntity {
  type: 'transcript';
  metadata: {
    language: string;
    duration: string;
    chunkCount: string;
    assetId?: string; // Referencia al audio si existe
  };
}

export interface ProjectEntity extends SemanticEntity {
  type: 'project';
  metadata: {
    description?: string;
  };
}

// Helper para crear IDs estables
export function makeStableId(type: EntityType, stablePart: string): string {
  const normalized = stablePart.toLowerCase().replace(/[^a-z0-9-_]/g, '_');
  return `${type}:${normalized}`;
}

// Helper para generar checksum simple (determinista)
export function simpleChecksum(input: string): string {
  let hash = 0;
  for (let i = 0; i < input.length; i++) {
    const char = input.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32bit integer
  }
  return Math.abs(hash).toString(16).padStart(8, '0');
}

export interface RelationTriple {
  subjectId: string;
  relation: string;
  objectId: string;
  weight: RelationWeight;
  metadata: Record<string, string>;
  source: string;
}

export interface RelationWeight {
  confidence: number;
  importance: number;
  emotionalAffinity?: number;
  activeAttitude?: number;
}

export type RelationSource = 'user' | 'system' | 'inferred' | 'imported';

